import type { Metadata } from "next";
import { Geist, Geist_Mono, Roboto } from "next/font/google";
import "./styles/globals.css";
import Container from "./components/common/Container/Container";
import { robotoFont } from "./fonts";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className={robotoFont.className}>
                {/* <header>
                    <div className="logo">
                        <img src="logo.png" alt="Логотип мебельного магазина" />
                    </div>
                    <div className="contacts">
                        <p>
                            Телефон: <a href="tel:+71234567890">+7 (123) 456-78-90</a>
                        </p>
                        <p>
                            Email: <a href="mailto:info@example.com">info@example.com</a>
                        </p>
                    </div>
                </header> */}

                {/* <nav>
                    <ul style={{ display: "flex", listStyle: "none", gap: 20 }}>
                        <li>
                            <a href="/tables">Столы</a>
                        </li>
                        <li>
                            <a href="/chairs">Стулья</a>
                        </li>
                        <li>
                            <a href="/wardrobes">Шкафы</a>
                        </li>
                        <li>
                            <a href="/sofas">Диваны</a>
                        </li>
                    </ul>
                </nav> */}
                <main>
                    <Container>{children}</Container>
                </main>

                {/* <footer>
                    <p>&copy; 2025 Мебельный Магазин. Все права защищены.</p>
                    <p>Адрес: ул. Примерная, д. 10, Москва</p>
                    <p>
                        Телефон: <a href="tel:+71234567890">+7 (123) 456-78-90</a>
                    </p>
                </footer> */}
            </body>
        </html>
    );
}
