import type { Metadata } from "next";
import { Geist, Geist_Mono, Roboto } from "next/font/google";
import "./styles/globals.css";
import Container from "./components/common/Container/Container";
import { robotoFont } from "./fonts";
import "react-toastify/dist/ReactToastify.css";
import { ToastContainer } from "react-toastify";
import { getOrInitSettings } from "@/Server/actions_DB/settingsActions";

import { auth, authOptions } from "@/lib/auth";

import { SignOutBtn } from "./components/auth/AuthButtons";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default async function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    // const settings = await getOrInitSettings(); // ПОДГРУЗКА НАСТРОЕК МАГАЗИНА

    const session = await auth();
    console.log("session🌟", session);

    return (
        <html lang="en">
            <body className={robotoFont.className}>
                <div>{JSON.stringify(session?.user?.name, null, 2)}</div>

                {/* <header>
                    <div className="logo">
                        <img src="logo.png" alt="Логотип мебельного магазина" />
                    </div>
                    <div className="contacts">
                        <p>
                            Телефон: <a href="tel:+71234567890">+7 (123) 456-78-90</a>
                        </p>
                        <p>
                            Email: <a href="mailto:info@example.com">info@example.com</a>
                        </p>
                    </div>
                </header> */}

                {/* <nav>
                    <ul style={{ display: "flex", listStyle: "none", gap: 20 }}>
                        <li>
                            <a href="/tables">Столы</a>
                        </li>
                        <li>
                            <a href="/chairs">Стулья</a>
                        </li>
                        <li>
                            <a href="/wardrobes">Шкафы</a>
                        </li>
                        <li>
                            <a href="/sofas">Диваны</a>
                        </li>
                    </ul>
                </nav> */}
                <main>
                    <ToastContainer />
                    <Container>{children}</Container>
                </main>

                {/* <footer>
                    <p>&copy; 2025 Мебельный Магазин. Все права защищены.</p>
                    <p>Адрес: ул. Примерная, д. 10, Москва</p>
                    <p>
                        Телефон: <a href="tel:+71234567890">+7 (123) 456-78-90</a>
                    </p>
                </footer> */}
            </body>
        </html>
    );
}
